name: Release

on:
  workflow_dispatch:
  
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{steps.create_release.outputs.upload_url}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          draft: true
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          
  build-windows:
    name: Build Windows
    needs: create_release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      run:
        dotnet restore
        
    - name: Run Image Processor
      working-directory: ${{github.workspace}}
      run: |
        msbuild .\FaustVst.sln /t:FaustImageProcessor /p:Configuration="Release" 
        FaustImageProcessor\bin\Release\net6.0-windows\FaustImageProcessor.exe
        
    - name: Run MSBuild for Plugin
      working-directory: ${{github.workspace}}
      run: msbuild .\FaustVst.sln /t:FaustVst /p:Configuration=Release

    - name: Add Plugin Archive
      working-directory: ${{github.workspace}}
      run: |
        mkdir plugin-build
        move FaustVst\bin\Release\net6.0-windows plugin-build\FaustVst
        cp FaustVst\README.txt plugin-build
        Compress-Archive -Path plugin-build\* -Destination FaustVST3Plugin.zip

    - name: Upload Plugin Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./FaustVST3Plugin.zip
        asset_name: FaustVST3Plugin.zip
        asset_content_type: application/zip
